# Generated by Django 3.2.7 on 2022-10-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('transportation', 'Transportation'), ('food', 'Food'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('medical_healthcare', 'Medical Healthcare'), ('saving', 'Saving'), ('personal', 'Personal'), ('other', 'Other')], max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.budget')),
            ],
        ),
    ]
