# Generated by Django 3.2.7 on 2022-10-22 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0002_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='shared',
            field=models.ManyToManyField(related_name='shared_budgets', to=settings.AUTH_USER_MODEL),
        ),
    ]
